City.IMS/ViewModels/CityViewModels.cs
using City.IMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace City.IMS.ViewModels
{
    public class CitycreateViewModels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public int Dwellers { get; set; }
        public string Location { get; set; }
        public string Weather { get; set; }
        public int countryId { get; set; }
        public List<Country> countries { get; set; }
    }
    public class CityListViewModel
    {
        public List<Citymodel> citymodels { get; set; }
    }
    public class CityListingViewModel
    {
        public string CityName { get; set; }
        public int? CountryId { get; set; }
        public List<Country> Countries { get; set; }
        public List<Citymodel> Citymodels { get; set; }
        public Pager Pager { get; set; }
    }
}

City.IMS/Controllers/CityController.cs
using City.IMS.Models;
using City.IMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace City.IMS.Controllers
{
    public class CityController : Controller
    {
        CityDbContext context = new CityDbContext();
        // GET: City
        public ActionResult Index()
        {
           
            return View();
        }
        public ActionResult Create()
        {
            CitycreateViewModels model = new CitycreateViewModels();
            model.countries = context.Countries.ToList();
            return PartialView(model);

        }
        [HttpPost]
        public JsonResult Create(CitycreateViewModels model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                var newCity = new Citymodel();
                newCity.Name = model.Name;
                newCity.About = model.About;
                newCity.Dwellers = model.Dwellers;
                newCity.Location = model.Location;
                newCity.Weather = model.Weather;
                newCity.Country = context.Countries.Find(model.countryId);

                context.Citymodels.Add(newCity);
                context.SaveChanges();
                
                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, message = "Invalid inputs." };
            }
            return result;
        }
        public ActionResult CityTable()
        {
            CityListViewModel model = new CityListViewModel();
            model.citymodels = context.Citymodels.ToList();

            return PartialView(model);
        }
        public ActionResult CityListing(string cityName,int? countryId, int? pageNo, int pageSize=3)
        {
            
            pageNo = pageNo ?? 1;
            int skipCount = (int)(pageSize * (pageNo - 1));
            CityListingViewModel model = new CityListingViewModel();
            model.CityName = cityName;
            model.CountryId = countryId;
            model.Countries = context.Countries.ToList();

            var citywithcountry = context.Citymodels.Include(c => c.Country).AsQueryable();
            if(!string.IsNullOrEmpty(cityName))
            {
                citywithcountry = citywithcountry.Where(c => c.Name.ToLower()
           .Contains(cityName.ToLower()));
            }
            if(countryId.HasValue && countryId.Value>0)
            {
                citywithcountry =citywithcountry.Where(c =>c.CountryId == countryId.Value);
            }
            var totalcity = citywithcountry.Count();
            model.Pager = new Pager(totalcity, pageNo, pageSize);
            model.Citymodels =citywithcountry.OrderByDescending(a => a.Name).Skip(skipCount).Take(pageSize).ToList();
          
            return View(model);
        }
    }
}

City.IMS/Views/City/CityListing.cshtml
@model City.IMS.ViewModels.CityListingViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var countryId = Model.CountryId.HasValue ? Model.CountryId.Value : 0;
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div  class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col col-lg-12">
                <h2>View Cities</h2>
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col col-lg-12">
                <form id="AuctionControlForm">
                    <div class="input-group">
                        <input type="text" id="searchTxt" name="search" class="form-control mr-1" placeholder="Search by title..." value="@Model.CityName">
                        @if (Model.Countries != null && Model.Countries.Count() > 0)
                        {
                            <select class="form-control mr-1" name="CountryId" id="selectCountry">
                                <option value="0" disabled selected>
                                    Select Category
                                </option>
                                @foreach (var country in Model.Countries)
                                {
                                    var selected = country.Id == countryId ? "selected" : string.Empty;
                                    <option value="@country.Id" @selected>
                                        @country.Name
                                    </option>
                                }
                            </select>
                        }


                        <div class="input-group-append link-danger" id="button-addon4">
                            <button id="searchBtn" class="btn btn-primary mr-1" type="button">Search</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div>

            <table class="table table-striped">
                <thead style="background-color:darkseagreen">
                    <tr>
                        <td>SL#</td>

                        <td>City Name</td>

                        <td>About</td>

                        <td>No. Of Dwellers</td>

                        <td>Location</td>

                        <td>Weather</td>

                        <td>Country</td>

                        <td>About Country</td>
                    </tr>

                </thead>
                <tbody>
                    @if (Model.Citymodels != null && Model.Citymodels.Count > 0)
                    {
                        foreach (var city in Model.Citymodels)
                        {
                            <tr>
                                <td>@city.Id</td>

                                <td>@city.Name</td>

                                <td>@city.About</td>

                                <td>@city.Dwellers</td>

                                <td>@city.Location</td>

                                <td>@city.Weather</td>

                                <td>@city.Country.Name</td>

                                <td>@city.Country.About</td>

                            </tr>
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="12" class="text-center alert alert-danger">
                                No City data found!!!.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @if (Model.Pager.CurrentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CityListing", "City", new { pageNo = Model.Pager.CurrentPage - 1, categoryId = Model.CountryId, search = Model.CityName })" style="cursor:pointer">Previous</a>
                            </li>
                        }
                        @for (int page = Model.Pager.StartPage; page < Model.Pager.EndPage + 1; page++)
                        {
                            var active = page == Model.Pager.CurrentPage ? "active" : string.Empty;
                            <li class="page-item @active">
                                <a class="pageDataLink page-link" data-href="@Url.Action("CityListing", "City", new { pageNo = page, categoryId = Model.CountryId, search = Model.CityName })" style="cursor:pointer">@page</a>
                            </li>
                        }
                        @if (Model.Pager.CurrentPage == Model.Pager.EndPage)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CityListing", "City", new { pageNo = Model.Pager.CurrentPage + 1, categoryId = Model.CountryId, search = Model.CityName })" style="cursor:pointer">Next</a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </div>
</div>

<script>
    $("#selectCountry").change(function () {
        $.ajax({
            url: '@Url.Action("CityListing", "City")',
            data: {
                search: $("#searchTxt").val(),
                countryId: $("#selectCountry").val()
            }

        })
            .done(function (response) {

                $("#ListingTable").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });

    $("#searchBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CityListing", "City")',
            data: {

                cityName: $("#searchTxt").val()
            }

        })
            .done(function (response) {

                $("#ListingTable").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
    $(".pageDataLink").click(function () {
        var url = $(this).attr("data-href");

        $.ajax({
            url: url
        })
            .done(function (response) {
                $("#ListingTable").html(response);
            })
            .fail(function () {
                alert("Fail");
            })
    });
</script>

City.IMS/Views/City/CityTable.cshtml
@model City.IMS.ViewModels.CityListViewModel

<table class="table">
    <thead>
        <tr>
            <th scope="col">SL#</th>
            <th scope="col">Name</th>
            <th scope="col">No. of Dwellers</th>
            <th scope="col">Country</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var city in Model.citymodels)
        {
        <tr>
            <th scope="row">@city.Id</th>
            <td>@city.Name</td>
            <td>@city.Dwellers</td>
            <td>@city.Country.Name</td>

        </tr>
        }

    </tbody>
</table>

City.IMS/Views/City/Create.cshtml
@model City.IMS.ViewModels.CitycreateViewModels


<form id="CreateTable">
    <div class="form-group">
        <label>Name</label>
        <input name="Name" type="text" class="form-control" placeholder="Enter your name" />
    </div>
    <div class="form-group">
        <label>About</label>
        <input type="text" class="form-control" name="About" placeholder="Write About">
    </div>
    <div class="form-group">
        <label>Dwellers</label>
        <input type="number" class="form-control" name="Dwellers">
    </div>
    <div class="form-group">
        <label>Location</label>
        <input type="text" class="form-control" name="Location">
    </div>
    <div class="form-group">
        <label>Weather</label>
        <input type="text" class="form-control" name="Weather">
    </div>
    <div class="form-group">
        <label>Country</label>
        <select class="form-control" name="countryId">
            @foreach (var country in Model.countries)
            {
                <option value="@country.Id">@country.Name</option>
            }
        </select>

    </div>
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
        <button type="button" id="saveBtn" class="btn btn-danger">Save</button>
        <button type="reset"class="btn btn-warning">Cancel</button>
    </div>
</form>

<script>

    $("#saveBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "City")',
            data: $('#CreateTable').serialize()
        })
            .done(function (response) {
                if (response.success) {
                    ReloadListing()
                } else {
                    console.log("error")
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    function ReloadListing() {
        $.ajax({
            url: '@Url.Action("CityTable", "City")',
            method: 'Get',
        })
        .done(function (response) {
            $("#citylistingArea").html(response);
        })
    }


</script>

City.IMS/Views/City/Index.cshtml
@model City.IMS.ViewModels.CitycreateViewModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="formArea">
    <div>
        @{
            Html.RenderAction("Create");
        }
    </div>
    <hr />
    <div id="citylistingArea">
        @{
            Html.RenderAction("CityTable");
        }
    </div>
    

</div>