City.IMS/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace City.IMS.Models
{
    public class Country
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public  ICollection<Citymodel> Citymodels { get; set; }
    }
}

City.IMS/ViewModels/CountryViewModel.cs
using City.IMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace City.IMS.ViewModels
{
    public class CountryViewModel
    {
        public List<Country> countries { get; set; }
    }
    public class CountryListingViewModel
    {
        public List<Country> countries { get; set; }
        public string CountryName { get; set; }
        public Pager Pager { get; set; }
        public List<Citymodel> Cities { get; set; }
    }
}

City.IMS/Controllers/CountryController.cs
using City.IMS.Models;
using City.IMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace City.IMS.Controllers
{
    public class CountryController : Controller
    {
        CityDbContext context = new CityDbContext();
        // GET: Country
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult Create()
        {
            return PartialView();

        }
        [HttpPost]
        public JsonResult Create (Country data)
        {
            JsonResult result = new JsonResult();
            if(ModelState.IsValid)
            {
                var model = new Country();

                model.Name = data.Name;
                model.About = data.About;

                context.Countries.Add(model);
                context.SaveChanges();
                
                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, message = "Invalid inputs." };
            }
            
            return result;
 
        }
        public ActionResult CountryTable()
        {
            CountryViewModel model = new CountryViewModel();

            model.countries= context.Countries.ToList();

            return PartialView(model);
        }
        public ActionResult CountryListing(string countryName,int? pageNo, int pageSize = 3)
        {

            pageNo = pageNo ?? 1;
            int skipCount = (int)(pageSize * (pageNo - 1));
            CountryListingViewModel model = new CountryListingViewModel();
            model.CountryName = countryName;
            
            var Allcountry = context.Countries.AsQueryable();
            
            if (!string.IsNullOrEmpty(countryName))
            {
                Allcountry = Allcountry.Where(c => c.Name.ToLower().Contains(countryName.ToLower()));
               
            }
           
            model.Pager = new Pager(Allcountry.Count(), pageNo, pageSize);
            model.countries = Allcountry.OrderBy(a => a.Name)
                                        .Skip(skipCount).Take(pageSize)
                                        .Include(a=>a.Citymodels)
                                        .ToList();

            return View(model);
        }
    }
}

City.IMS/Views/Country/CountryListing.cshtml
@model City.IMS.ViewModels.CountryListingViewModel
@{
    ViewBag.Title = "CountryListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CountryListing</h2>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col col-lg-12">
                <h2>View Countries</h2>
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col col-lg-12">
                <form id="CountryForm">
                    <div class="input-group">
                        <input type="text" id="searchTxt" name="search" class="form-control mr-1" placeholder="Search by title..." value="@Model.CountryName">
                        <div class="input-group-append link-danger" id="button-addon4">
                            <button id="searchBtn" class="btn btn-primary mr-1" type="button">Search</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div>

            <table class="table table-striped">
                <thead style="background-color:darkseagreen">
                    <tr>
                        <td>SL#</td>

                        <td>Country Name</td>

                        <td>About</td>

                        <td>No. Of Cities</td>

                        <td>No. Of Dwellers</td>
                    </tr>

                </thead>
                <tbody>
                    @if (Model.countries != null && Model.countries.Count > 0)
                    {
                        foreach (var country in Model.countries)
                        {
                            <tr>
                                <td>@country.Id</td>

                                <td>@country.Name</td>

                                <td>@country.About</td>

                                <td>@country.Citymodels.Count</td>

                                <td>@country.Citymodels.Sum(a=>a.Dwellers)</td>
                            </tr>
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="12" class="text-center alert alert-danger">
                                No Country data found!!!.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @if (Model.Pager.CurrentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CountryListing", "Country", new { pageNo = Model.Pager.CurrentPage - 1,search = Model.CountryName })" style="cursor:pointer">Previous</a>
                            </li>
                        }
                        @for (int page = Model.Pager.StartPage; page < Model.Pager.EndPage + 1; page++)
                        {
                            var active = page == Model.Pager.CurrentPage ? "active" : string.Empty;
                            <li class="page-item @active">
                                <a class="pageDataLink page-link" data-href="@Url.Action("CountryListing", "Country", new { pageNo = page,search = Model.CountryName })" style="cursor:pointer">@page</a>
                            </li>
                        }
                        @if (Model.Pager.CurrentPage == Model.Pager.EndPage)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CountryListing", "Country", new { pageNo = Model.Pager.CurrentPage + 1,search = Model.CountryName })" style="cursor:pointer">Next</a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </div>
</div>

<script>
    $("#searchBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CountryListing", "Country")',
            data: {

                CountryName: $("#searchTxt").val()
            }

        })
            .done(function (response) {

                $("#ListingTable").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
    $(".pageDataLink").click(function () {
        var url = $(this).attr("data-href");

        $.ajax({
            url: url
        })
            .done(function (response) {
                $("#ListingTable").html(response);
            })
            .fail(function () {
                alert("Fail");
            })
    });
</script>

City.IMS/Views/Country/CountryTable.cshtml
@model City.IMS.ViewModels.CountryViewModel

<table class="table">
    <thead>
        <tr>
            <th scope="col">SL#</th>
            <th scope="col">Name</th>
            <th scope="col">About</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var country in Model.countries)
        {
            <tr>
                <th scope="row">@country.Id</th>
                <td>@country.Name</td>
                <td>@country.About</td>

            </tr>
        }

    </tbody>
</table>

City.IMS/Views/Country/Create.cshtml
@model City.IMS.Models.Country


<form id="CreateTable">
    <div class="modal-body">
        <div class="form-group">
            <label>Name</label>
            <input id="name" name="Name" type="text" class="form-control" placeholder="Enter your name" />
        </div>
        <div class="form-group">
            <label>About</label>
            <input class="form-control" name="About" placeholder="Write About">
        </div>
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <button type="button" id="saveBtn" class="btn btn-success">Save</button>
            <button type="reset"class="btn btn-secondary">Cancel</button>
        </div>
    </div>
</form>

<script>

    $("#saveBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Country")',
            data: $('#CreateTable').serialize()
        })
            .done(function (response) {
                if (response.success) {
                    ReloadListing()
                       
                } else {
                    console.log("error")
                }

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

     function ReloadListing() {
        $.ajax({
            url: '@Url.Action("CountryTable", "Country")',
            method: 'Get',
        })
        .done(function (response) {
            $("#countrylistingArea").html(response);
        })
    }
  

</script>

City.IMS/Views/Country/Index.cshtml
<div>
    <div id="formArea">
        @{
            Html.RenderAction("Create");
        }
    </div>
    <hr />
    <div id="countrylistingArea">
        @{
            Html.RenderAction("CountryTable");
        }
    </div>

</div>